[package]
name = "birdseye"
version = "0.1.0"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { git = "https://github.com/emilk/egui.git", features = ["serde"] }
egui_glium = { git = "https://github.com/emilk/egui.git" }
#diskspace_insight = "*"
diskspace_insight = { path = "../diskspace-insight" }
dirs = "*"

# serde = { version = "1", features = ["derive"] }

# egui = { path = "../egui", features = ["serde"] }
# egui = "0.1.4"
# egui_glium = "0.1.3"
#serde = { version = "1", features = ["derive"] }




#git@github.com:emilk/egui.git