name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    steps:
    - uses: actions/checkout@v2
    - name: Install xcb
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      run: cargo check
    - name: Run tests
      run: cargo test