name: Rust Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    steps:
    - uses: actions/checkout@v2
    - name: Install xcb
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: target/release/birdseye
    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: target/release/birdseye.exe
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
      